### ISSUE TITLE
Please, document fields query parameter syntax

### ISSUE THREAD

**Issue by carlosjac** [illuminatech/data-provider#2]
Thank you very much for sharing this package.

My controller has this code

        $query = Customer::query() 
        ->with('country')
        $customers = DataProvider::new($query)
            ->filters([
                'id',
                'organization_id',
                'country_id',
                'legal_id_type_id',
                'vat_condition_id',
                'legal_id_number',
                'customer_type_id',
                'search' => ['name', 'contact_last_name', 'contact_first_name', 'contact_email' ],
                'name' => new FilterSearch(['name']),
                'contact_last_name' => new FilterSearch(['contact_last_name']),
                'contact_first_name' => new FilterSearch(['contact_first_name']),
                'contact_email' => new FilterSearch(['contact_email']),

            ])
            ->fields(['id', 'created_at', 'updated_at', 'organization_id', 'name', 'address', 'country_id', 'legal_id_type_id', 'vat_condition_id', 'legal_id_number', 'notify_charge_by_email', 'notify_collection_by_email',  'delayed_payment_notification_policy_id', 'contact_last_name', 'contact_first_name', 'contact_email', 'contact_landphone', 'contact_cellphone', 'customer_type_id', 'country' => ['id', 'name']  ])
            ->sort(['id', 'name'])
            ->sortDefault('id')
            ->includes(['country'])
            ->paginate(request());

Note that I've added an include 'country'.  Also, I've added  country id and coountry name in fields

This works fine if I request

https://timci.lndo.site/api/customers?fields[]=id,name

but I don't know how to ask for country name in query string.
I've tried with

https://timci.lndo.site/api/customers?fields[]=id,name,country.name

but that throws 

Illuminatech\DataProvider\Exceptions\InvalidQueryException: Unsupported field &quot;id,name,country.name&quot; in &quot;fields&quot;. in file /app/app/vendor/illuminatech/data-provider/src/Selector.php on line 301

#0 /app/app/vendor/illuminatech/data-provider/src/Selector.php(278): Illuminatech\DataProvider\Selector-&gt;applyFieldsRecursive(Object(Illuminate\Database\Eloquent\Builder), Array, Array, Array)
#1 /app/app/vendor/illuminatech/data-provider/src/Selector.php(230): Illuminatech\DataProvider\Selector-&gt;applyFields(Object(Illuminate\Database\Eloquent\Builder), Array)
#2 /app/app/vendor/illuminatech/data-provider/src/DataProvider.php(157): Illuminatech\DataProvider\Selector-&gt;apply(Object(Illuminate\Database\Eloquent\Builder), Array)
#3 /app/app/vendor/illuminatech/data-provider/src/DataProvider.php(216): Illuminatech\DataProvider\DataProvider-&gt;prepare(Array)
#4 /app/app/app/Http/Controllers/Api/CustomerController.php(74): Illuminatech\DataProvider\DataProvider-&gt;paginate(Object(Illuminate\Http\Request))
#5 /app/app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Api\CustomerController-&gt;index()
#6 /app/app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller-&gt;callAction('index', Array)
#7 /app/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\Routing\ControllerDispatcher-&gt;dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\CustomerController), 'index')
#8 /app/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route-&gt;runController()
#9 /app/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\Routing\Route-&gt;run()
#10 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /app/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /app/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /app/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(103): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handleRequest(Object(Illuminate\Http\Request), Object(Closure), Array)
#15 /app/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(55): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handleRequestUsingNamedLimiter(Object(Illuminate\Http\Request), Object(Closure), 'api', Object(Closure))
#16 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#17 /app/app/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate-&gt;handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#19 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /app/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#21 /app/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\Routing\Router-&gt;runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#22 /app/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router-&gt;runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#23 /app/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#24 /app/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#25 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#26 /app/app/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /app/app/vendor/matthewbdaly/laravel-dynamic-serving/src/Http/Middleware/DetectMobile.php(58): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Matthewbdaly\LaravelDynamicServing\Http\Middleware\DetectMobile-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /app/app/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /app/app/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Http\Middleware\TrustProxies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /app/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /app/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /app/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /app/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /app/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /app/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /app/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /app/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#46 /app/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#47 /app/app/public/index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#48 {main}

Thank you in advance for any help you can give to me

**Comment by klimov-paul** [comment]
See: https://github.com/illuminatech/data-provider/blame/1.0.3/README.md#L483-L500

In your case it should be:

```
$request = [
    'fields' => [
        'id',
        'name',
        'country' => [
            'name',
        ],
    ],
];
dump(http_build_query($request));
// "fields[0]=id&fields[1]=name&fields[country][0]=name"
```
