### ISSUE TITLE
Discussion - Do you need to create multiple DataProvider to differentiate between collection and model?

### ISSUE THREAD

**Issue by rizaldywirawan** [illuminatech/data-provider#5]
Since there is no discussion section, I will ask here.

First of all, thank you for the package! It really suites the way I use action class. I hope you have a great day!

Here is my question:

API endpoint: `/products`
Let's say you have a `DataProvider` for a Product model, the input will be a `Builder` you will have functionality for filter and include, and it will print the `get()` result (collection).

At the sametime, you will have API endpoint: `/products/{product}`.
There won't be filter or sort, it's only include, because sometimes we will have to dynamically call the relationship data.

Do you think you will need to create a different `DataProvider`, or just use the same one, and why? 

Thank you

**Comment by klimov-paul** [comment]
In general `DataProvider` is not meant to be used for the particular entity details display.
However, you may reuse the same configuration or dedicated data provider for this:

```php
class ProductDataProvider extends DedicatedDataProvider
{
    protected function defineConfig(): array
    {
        return [
            'pagination' => [
                'per_page' => [
                    'default' => 16,
                ],
            ],
            // ...
        ];
    }

    protected function defineIncludes(): array
    {
        return [
            'category',
            // ...
        ];
    }
}

class ProductController
{
    public function index(Request $request)
    {
        $query = Product::query();
        $productsWithPagination = ProductDataProvider::new($query)
            ->paginate($request);
        // ...
    }

    public function show(Request $request, string $id)
    {
        $query = Product::query()->where('id', $id);
        $soleProduct = $productsWithPagination = ProductDataProvider::new($query)
            ->prepare($request)
            ->first();
        // ...
    }
}
```
