### ISSUE TITLE
Define dynamic value for the include relationship

### ISSUE THREAD

**Issue by rizaldywirawan** [illuminatech/data-provider#7]
### What steps will reproduce the problem?
I try to create a dynamic include relationship, but unable to make a dynamic input value for it

### What is the expected result?
We can define an include that has dynamic value as the parameter.

### What do you get instead?
Currently nothing.

### Additional info
Is this possible? In the example, we have a custom include with new IncludeRelation callback, but the value is hard-coded, is it possible to make it dynamic? 

Thank you !

| Q                         | A
| ------------------------- | ---
| This Package Version      | 1.0.5
| Laravel Framework Version | 10.23.1
| PHP version               |  8.2
| Operating system          | Windows 11

**Comment by klimov-paul** [comment]
The provided description is too bizarre for me to be certain, what it is about.

Still if you define a particular include as a callback you can process any data you want inside it, which includes raw request:

```php
public function index(Request $request)
{
    $dataProvider = DataProvider::new(Item::class)
        ->includes([
            'comments' => new IncludeRelation('comments', function ($commentsQuery) use ($request) {
                $commentsQuery->where('status', '=', $request->query('includes')['comments'']['params']['status']);
            }),
        ]);

        // ...
}
```

**Comment by rizaldywirawan** [comment]
Is it considered okay, if we pass more than one value to the `DedicatedProvider`?
